sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'gem install compass --pre --no-ri --no-rdoc'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'npm install'
